### PR TITLE
chore: bump erlang/elixir to sonoma friendly versions

### PR DESCRIPTION
**Pull request by Whoops**
#### Summary of changes

Updating Erlang to a version that works on Sonoma

### CODE REVIEW

**Comment by Whoops** [comment]
Not bumping straight to Erlang 26 and Elixir 1.15 due to [issues with old dependencies](https://app.asana.com/0/1204137169527258/1205823045134240/f) we should sort out. Erlang 25.3.2.7 seems to resolve the Sonoma issues in the meantime.

**Comment by nlwstein** [comment]
@Whoops The Dockerfile (and perhaps other locations related to CI) does not pull from the ASDF config: https://github.com/mbta/api/blob/master/Dockerfile

**Review by nlwstein — CHANGES_REQUESTED** [review]
(Added comment prior to submitting review - mainly just double check that CI builds pull the same version 🙂 otherwise this looks good!)

**Comment by Whoops** [comment]
Good eye! I knew we we using ASDF for CI, but didn't think to check the Dockerfile. I checked for other instances of hardcoded versions and didn't find any, so I think this covers it now.

**Review by nlwstein — APPROVED** [review]
🚀

**Pull request merged**
