### PR TITLE
ci: fix asana workflow for dependabot

### PR DESCRIPTION
**Pull request by paulswartz**
#### Summary of changes

**Asana Ticket:** [TICKET_NAME](TICKET_LINK)

[Please include a brief description of what was changed]

### CODE REVIEW

**Comment by paulswartz** [comment]
@bklebe it looks like this still needs the `if` block for the repository. I suppose it could move into the shared action as well, but that would potentially make it less useful for non-MBTA repositories (if we care about that).

**Comment by bklebe** [comment]
@paulswartz: the `if` block meaning your change about checking the repository owner, or something else?

**Comment by paulswartz** [comment]
Yep, checking the repository owner.

**Comment by bklebe** [comment]
> it looks like this still needs the if block for the repository.

Do you know why this is needed here but not RTR? Is it because you run a fork of this repo?


> I suppose it could move into the shared action as well, but that would potentially make it less useful for non-MBTA repositories (if we care about that).

I don't personally care about it very much. We could always add it as a parameter with a default value though. I'll defer to you what's best here; I think using the shared workflow is nice because it's one less difference to maintain between this app and others.

**Comment by paulswartz** [comment]
> Do you know why this is needed here but not RTR? Is it because you run a fork of this repo?

@bklebe I think that's right. I'll look at the shared workflow to see if I can add the relevant check there.

**Review by bklebe — CHANGES_REQUESTED** [review]
Looks like this now has a merge conflict. I approved the update to the shared workflow though, so hopefully now you can use that?

**Comment by bklebe** [comment]
@meagharty is this still relevant?

**Comment by meagharty** [comment]
Closing this since it was fixed in https://github.com/mbta/api/pull/702

**Pull request closed without merging**
